Feature/basic design/CMOB-1302
ninikokra/SPACE-ChatApp pull request #4
Opened 2023-04-15 16:15 UTC by ninikokra

https://spaceneobank.atlassian.net/browse/CMOB-1302

2023-04-15 16:50 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/space_chatapp/Presentation/MziaScreen/MziaFragment.kt
> +class MziaFragment : BaseFragment<FragmentMziaBinding>(){
very strange name for fragment)

2023-04-15 18:07 UTC, Gio481 commented on app/src/main/java/com/example/space_chatapp/Presentation/MziaScreen/MziaFragment.kt
> +
onBind ში ხო უნდა დაიწეროს ლოგიკები ამიტო ინფლეიტის ქვეშ რო იყოს უკეთესია, მეორე ფრაგმენტშიც

2023-04-15 18:07 UTC, Gio481 commented on app/src/main/res/layout/fragment_mzia.xml
> +        android:layout_marginEnd="@dimen/dimen_8dp"
marginHorizontal

2023-04-15 18:08 UTC, Gio481 commented on app/src/main/res/layout/fragment_mzia.xml
> +        android:minHeight="48dp"
48dp რესურსებში

2023-04-15 18:08 UTC, Gio481 approved these changes

2023-04-17 11:19 UTC, ninikokra commented on app/src/main/java/com/example/space_chatapp/Presentation/MziaScreen/MziaFragment.kt
> +
Done

2023-04-17 11:19 UTC, ninikokra commented on app/src/main/res/layout/fragment_mzia.xml
> +        android:minHeight="48dp"
Done

2023-04-17 11:20 UTC, ninikokra commented on app/src/main/res/layout/fragment_mzia.xml
> +        android:layout_marginEnd="@dimen/dimen_8dp"
done

2023-04-18 09:08 UTC, gioqemoklidze requested changes

2023-04-18 09:08 UTC, gioqemoklidze commented on app/src/main/java/com/example/space_chatapp/Presentation/MziaScreen/MziaFragment.kt
> +        return FragmentMziaBinding::inflate
სახელი

2023-04-18 09:08 UTC, gioqemoklidze commented on app/src/main/java/com/example/space_chatapp/Presentation/ZezvaScreen/ZezvaFragment.kt
> +}
სახელი  :D :D

2023-04-18 09:08 UTC, gioqemoklidze commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/zezvaFragment"
სახელი

2023-04-18 09:08 UTC, gioqemoklidze commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/mziaFragment"
აქაც :DDDDD

2023-04-18 09:08 UTC, gioqemoklidze commented on app/src/main/res/layout/fragment_mzia.xml
> +        android:id="@+id/mziaET"
იდ შესაცვლელია აქაც

2023-04-18 09:08 UTC, gioqemoklidze commented on app/src/main/res/layout/fragment_mzia.xml
> +        android:minHeight="48dp"
@ninikokra გამოგრჩა მემგონი

2023-04-18 09:08 UTC, gioqemoklidze commented on app/src/main/res/layout/fragment_zezva.xml
> +        android:id="@+id/zezvaET"
აქც აიდი შეუცვალე

2023-04-18 09:08 UTC, gioqemoklidze commented on app/src/main/res/layout/fragment_zezva.xml
> +        android:layout_marginEnd="@dimen/dimen_8dp"
marginHorizontal

2023-04-18 09:08 UTC, gioqemoklidze commented on app/src/main/res/layout/fragment_zezva.xml
> +        android:minHeight="48dp"
დიმენშენებში

2023-04-18 09:08 UTC, gioqemoklidze commented on app/src/main/res/layout/fragment_mzia.xml
> +        android:layout_marginEnd="@dimen/dimen_8dp"
@ninikokra ესეც გამორჩენილიგაქ და შენთვითონ ნუ დაარეზოლვებ ხოლმე რევიუვერმა უნდა დაარეზოლვოს მეორედ რევიუს მერე

2023-04-18 10:15 UTC, gioqemoklidze requested changes

2023-04-18 10:15 UTC, gioqemoklidze commented on app/src/main/java/com/example/space_chatapp/Presentation/BaseFragment.kt
> +        return binding.root
if (_binding == null) {
            _binding = bindingInflater(inflater, container, false)
        } 

დაგაზღვევს რო თუ უკვეაქვს ბაინდინგს მნიშვენლობა მეორედ აღარ მიენიჭოს

2023-04-18 10:22 UTC, ninikokra commented
ახალი რეპოზიტორი გავაკეთე, გარკვეული პრობლემების გამო 
https://github.com/ninikokra/SPACE--Chat
ამას დავხურავ. მადლობა :* <3

2023-04-18 10:22 UTC, closed without merging